language: csharp
solution: RailPhase.sln
install:
  - nuget restore RailPhase.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:ToolsVersion="4.0" RailPhase.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RailPhase.Tests/bin/Release/RailPhase.Tests.dll
after_success:
  - bash <(curl -s https://codecov.io/bash)
